# Comment arb-dir: lib/l10n when run: flutter gen-l10n
# or
# dart run crowdin_sdk:gen
# use only for: dart run split_intl:generate
# arb-dir: lib/l10n
synthetic-package: false
nullable-getter: false
template-arb-file: app_en.arb
output-dir: lib/core/application/localization
output-localization-file: app_localizations.dart
#output-class: Localizer
