final screenNames = {
  'EducationRoute': 'Education Screen',
  'DashboardRoute': 'Calendar Screen',
  'AccountRoute': 'User profile Screen',
  'LogWeightRoute': 'Today' 's weight Screen',
  'SelectFoodRoute': 'Select Food Screen',
  'BarcodeScannerRoute': 'Barcode Scanner ',
  'SearchRoute': 'Search Screen',
  'RecipeRoute': 'Recipe Screen',
  'SelectServingRoute': 'Select Serving Screen',
  'ProxyRoute': 'Proxy Screen',
  'IntroRoute': 'Intro Screen',
  'JoinUsRoute': 'Join Us Screen',
  'HeightRoute': 'Height Screen',
  'WeightRoute': 'Weight Screen',
  'BirthdayRoute': 'Birthday Screen',
  'SexRoute': 'Sex Screen',
  'BiologicalGenderRoute': 'Biological Gender Screen',
  'MedicalIntroRoute': 'Medical Intro Screen',
  'PregnancyRoute': 'Pregnancy Screen',
  'PregnancyFailedRoute': 'Pregnancy Failed Screen',
  'CardiovascularDiseaseRoute': 'Cardiovascular Disease Screen',
  'CardiovascularDiseaseFailedRoute': 'Cardiovascular Disease Failed Screen',
  'StomachReductionRoute': 'Stomach Reduction Screen',
  'StomachReductionFailedRoute': 'Stomach Reduction Failed Screen',
  'MedicalCheckPassedRoute': 'Medical Check Passed Screen',
  'PainInChestRoute': 'Pain In Chest Screen',
  'PainInChestFailedRoute': 'Pain In Chest Failed Screen',
  'TreatmentByDoctorRoute': 'Treatment By Doctor Screen',
  'TreatmentByDoctorFailedRoute': 'Treatment By Doctor Failed Screen',
  'WeightLossMedicationRoute': 'Weight Loss Medication Screen',
  'MedicationPastPeriodRoute': 'Medication Past Period Screen',
  'MedicationFuturePeriodRoute': 'Medication Future Period Screen',
  'PhysicalCheckResultRoute': 'Physical Check Result Screen',
  'ConsentNeededRoute': 'Consent Needed Screen',
  'LoginRoute': 'Login Screen',
  'ForgotPasswordRoute': 'Forgot Password Screen',
  'ResetPasswordRoute': 'Reset Password Screen',
  'SignUpWelcomeRoute': 'Sign Up Screen',
  'NameRoute': 'User Name Screen',
  'PasswordRoute': 'User Password Screen',
  'EmailAddressRoute': 'User Email Address Screen',
  'WaitingForConfirmationRoute': 'User Confirmation Screen',
  'CheckFailedAgeRoute': 'Check Failed Age Screen',
  'ConsentConfirmationRoute': 'Consent Confirmation Screen',
  'NoConsentRoute': 'No Consent Screen',
  'LegalStatementRoute': 'Legal Statement Screen',
  'PreferencesOverviewRoute': 'Preferences Overview Screen',
  'DiabetesRoute': 'Diabetes Screen',
  'DisclaimerRoute': 'Disclaimer Screen',
  'SummaryRoute': 'Summary Screen',
  'NutritionInstructionsRoute': 'Nutrition Instructions Screen',
  'MealRoute': 'Meal Screen',
  'LogPlannedMealsRoute': 'Log Planned Meals Screen',
  'RecipeDetailsRoute': 'Recipe Details Screen',
  'DishDetailsRoute': 'Dish Details Screen',
  'EditDishRoute': 'Edit Dish Screen',
  'LessonRoute': 'Lesson Screen',
  'LessonCompleteRoute': 'Lesson Complete Screen',
  'LessonErrorRoute': 'Lesson Error Screen',
  'SelectExerciseRoute': 'Select Exercise Screen',
  'DailyIntakeRoute': 'Daily Intake Screen',
  'ProgramAssessmentRoute': 'Program Assessment Screen',
  'PhysicalProgramsRoute': 'Physical Programs Screen',
  'ProgramDetailsRoute': 'Program Details Screen',
  'FoodPreferencesRoute': 'Food Preferences Screen',
  'EditFoodPreferencesRoute': ' Edit Food Preferences Screen',
  'JoinGroupPreferencesRoute': 'Join Group Preferences Screen',
  'GenderPreferencesRoute': 'User Gender Preferences Screen',
  'NicknamePreferencesRoute': 'Nickname Preferences Screen',
  'VideoRoute': 'Video Screen',
  'ReflectionRoute': 'Reflection Screen',
  'NutritionDetailsRoute': 'Nutrition Details Screen',
  'VideoSessionRoute': 'Video Session Screen',
  'GroupPreferencesRoute': 'Group Preferences Screen',
  'TimezonePreferencesRoute': 'Timezone Preferences Screen',
  'GroupRulesOneRoute': 'Group Rules One Screen',
  'GroupRulesTwoRoute': 'Group Rules Two Screen',
  'GroupRulesThreeRoute': 'Group Rules Three Screen',
  'GroupRulesFourRoute': 'Group Rules Four Screen',
  'GroupRulesFiveRoute': 'Group Rules Five Screen',
  'GroupRulesSixRoute': 'Group Rules Six Screen',
  'SupportGroupIntroRoute': 'Support Group Intro Screen',
};
